
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="mecanum_bot">
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_separation_x" value="0.5"/>
  <xacro:property name="wheel_separation_y" value="0.5"/>
  <link name="base_link">
    <visual><geometry><box size="0.6 0.6 0.1"/></geometry></visual>
  </link>
  <gazebo>
    <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <remapping>cmd_vel:=/cmd_vel</remapping>
      </ros>
      <update_rate>100</update_rate>
      <wheel_separation>${wheel_separation_x}</wheel_separation>
      <wheel_diameter>${2 * wheel_radius}</wheel_diameter>
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
    </plugin>
  </gazebo>
</robot>
